### ISSUE TITLE
LiveQuery Server Support

### ISSUE THREAD

**Issue by mattrothenberg** [cf-platform-eng/pws-parse-server#2]
First, thanks a TON for creating this repo. This was a huge help to get Parse deployed on PWS.

It would be helpful to include documentation on how to hook up Parse LiveQuery support, too. To that end, here are a few lines of configuration that got my app successfully running.

In your Parse Server `server.js`, add an array indicating the classes for which you'd like LiveQuery Support, and create the LiveQuery server.

```
var parseServer = new ParseServer({
  ...
  liveQuery: {
    classNames: ["Friends", "Photos"] // List of classes to support for query subscriptions
  }
});
...
var parseLiveQueryServer = ParseServer.createLiveQueryServer(server); // where server is your Express application.

```

In your client application, you'll need to specify the URL of your Parse LiveQuery server. I'm not 100% sure about this, but I read that PWS-deployed applications only support the `wss://` protocol, and that any websocket connections must occur on port `4443`.

```
Parse.liveQueryServerURL = 'wss://your-server-url.cfapps.io:4443';
```

Let me know if this helps!

**Comment by frodenas** [comment]
Thanks @mattrothenberg! I'm not actively maintaining this repo, but will accept a PR!
